export const HOME_DEMO_ASSETS = {
  personnelAppMobile: '/home/personnel-app-mobile.png',
  dashboardPreview: '/home/dashboard-preview.png',
  downloadPerson: '/home/download-person.png',
  storyImages: [
    '/home/stories/story-1.png',
    '/home/stories/story-2.png',
    '/home/stories/story-3.png',
    '/home/stories/story-4.png',
    '/home/stories/story-5.png',
  ],
  brandLogos: {
    YAPIKON: '/home/logos/yapikon.svg',
    KENTYAPI: '/home/logos/kentyapi.svg',
    'VİRA İNŞAAT': '/home/logos/vira-insaat.svg',
    'ALFA GRUP': '/home/logos/alfa-grup.svg',
    'NEXUS YAPI': '/home/logos/nexus-yapi.svg',
    'METRO İNŞAAT': '/home/logos/metro-insaat.svg',
    'DOĞU YAPI': '/home/logos/dogu-yapi.svg',
    'GÜNEŞ GRUP': '/home/logos/gunes-grup.svg',
    'MARMARA BETON': '/home/logos/marmara-beton.svg',
    'ANKARA PROJE': '/home/logos/ankara-proje.svg',
    'TEK ŞANTİYE': '/home/logos/tek-santiye.svg',
    'BETA YAPI': '/home/logos/beta-yapi.svg',
    'ÇELİK YAPI': '/home/logos/celik-yapi.svg',
    'DELTA İNŞAAT': '/home/logos/delta-insaat.svg',
  },
} as const;
